# Generated by Django 3.1.7 on 2021-03-20 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210320_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
