# Generated by Django 3.1.7 on 2021-03-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210328_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complete',
            new_name='ordered',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='slug',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
