# Generated by Django 3.1.7 on 2021-03-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_orderitem_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='user',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
