# Generated by Django 3.1.7 on 2021-04-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_orderitem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
