# Generated by Django 3.1.7 on 2021-04-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_orderitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='customer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
